version: '3.5'

services:
  postgres:
    container_name: card-postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:  postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    depends_on:
      - postgres
    container_name: card-postgres-admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "3333:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
